In [11]:
from rembg import remove
from PIL import Image

input = Image.open('c:/queenit/(1+1) 타미힐피거 반팔티 T3139 남성여성 2장세트.jpeg') # load image
output = remove(input) # remove background
output.save('rembg.png') # save image

In [5]:
import torch
import cv2
import matplotlib.pyplot as plt
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
# YOLOv5 모델 로드
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # 'yolov5s'는 작은 모델, 'yolov5l'은 큰 모델

# 이미지 로드
img = cv2.imread('c:/queenit/(1+1) 타미힐피거 반팔티 T3139 남성여성 2장세트.jpeg')  # 여기에 실제 이미지 경로를 입력
print(cv2.imread('c:/queenit/(1+1) 타미힐피거 반팔티 T3139 남성여성 2장세트.jpeg')) 
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# 객체 탐지
results = model(img_rgb)

# 결과 출력
results.render()
print(results.xyxy[0])  # 탐지된 객체 정보
plt.imshow(results.render()[0])
plt.show()

Using cache found in C:\Users\user/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2023-9-12 Python-3.10.11 torch-2.0.1+cpu CPU

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


[array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        ...,
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],
 
        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
  

tensor([[1.25718e+02, 1.37355e+02, 3.64454e+02, 3.71035e+02, 2.82001e-01, 2.50000e+01]])
